const CACHE_NAME = "array-duel-v137";
const ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./app.js",
  "./manifest.webmanifest",
  "./icon.svg",
  "./assets/xianxia-duel-aigei.mp3",
  "./assets/ui/ai-avatar.jpg",
  "./assets/ui/start-bg.jpg",
  "./assets/ui/start-bg-cover.jpg",
  "./assets/ui/battle-bg.jpg",
  "./assets/ui/battle-bg.svg",
  "./assets/ui/card-back.jpg",
  "./assets/cards/manifest.json",
  "./assets/cards/earth-01.jpg",
  "./assets/cards/earth-02.jpg",
  "./assets/cards/earth-03.jpg",
  "./assets/cards/earth-04.jpg",
  "./assets/cards/earth-05.jpg",
  "./assets/cards/earth-06.jpg",
  "./assets/cards/earth-07.jpg",
  "./assets/cards/earth-08.jpg",
  "./assets/cards/earth-09.jpg",
  "./assets/cards/earth-10.jpg",
  "./assets/cards/earth-11.jpg",
  "./assets/cards/earth-12.jpg",
  "./assets/cards/earth-13.jpg",
  "./assets/cards/earth-14.jpg",
  "./assets/cards/earth-15.jpg",
  "./assets/cards/earth-16.jpg",
  "./assets/cards/earth-17.jpg",
  "./assets/cards/earth-18.jpg",
  "./assets/cards/earth-19.jpg",
  "./assets/cards/eye-01.jpg",
  "./assets/cards/eye-02.jpg",
  "./assets/cards/eye-03.jpg",
  "./assets/cards/eye-04.jpg",
  "./assets/cards/eye-05.jpg",
  "./assets/cards/fire-01.jpg",
  "./assets/cards/fire-02.jpg",
  "./assets/cards/fire-03.jpg",
  "./assets/cards/fire-04.jpg",
  "./assets/cards/fire-05.jpg",
  "./assets/cards/fire-06.jpg",
  "./assets/cards/fire-07.jpg",
  "./assets/cards/fire-08.jpg",
  "./assets/cards/fire-09.jpg",
  "./assets/cards/fire-10.jpg",
  "./assets/cards/fire-11.jpg",
  "./assets/cards/fire-12.jpg",
  "./assets/cards/fire-13.jpg",
  "./assets/cards/fire-14.jpg",
  "./assets/cards/fire-15.jpg",
  "./assets/cards/fire-16.jpg",
  "./assets/cards/fire-17.jpg",
  "./assets/cards/fire-18.jpg",
  "./assets/cards/fire-19.jpg",
  "./assets/cards/metal-01.jpg",
  "./assets/cards/metal-02.jpg",
  "./assets/cards/metal-03.jpg",
  "./assets/cards/metal-04.jpg",
  "./assets/cards/metal-05.jpg",
  "./assets/cards/metal-06.jpg",
  "./assets/cards/metal-07.jpg",
  "./assets/cards/metal-08.jpg",
  "./assets/cards/metal-09.jpg",
  "./assets/cards/metal-10.jpg",
  "./assets/cards/metal-11.jpg",
  "./assets/cards/metal-12.jpg",
  "./assets/cards/metal-13.jpg",
  "./assets/cards/metal-14.jpg",
  "./assets/cards/metal-15.jpg",
  "./assets/cards/metal-16.jpg",
  "./assets/cards/metal-17.jpg",
  "./assets/cards/metal-18.jpg",
  "./assets/cards/metal-19.jpg",
  "./assets/cards/water-01.jpg",
  "./assets/cards/water-02.jpg",
  "./assets/cards/water-03.jpg",
  "./assets/cards/water-04.jpg",
  "./assets/cards/water-05.jpg",
  "./assets/cards/water-06.jpg",
  "./assets/cards/water-07.jpg",
  "./assets/cards/water-08.jpg",
  "./assets/cards/water-09.jpg",
  "./assets/cards/water-10.jpg",
  "./assets/cards/water-11.jpg",
  "./assets/cards/water-12.jpg",
  "./assets/cards/water-13.jpg",
  "./assets/cards/water-14.jpg",
  "./assets/cards/water-15.jpg",
  "./assets/cards/water-16.jpg",
  "./assets/cards/water-17.jpg",
  "./assets/cards/water-18.jpg",
  "./assets/cards/water-19.jpg",
  "./assets/cards/wood-01.jpg",
  "./assets/cards/wood-02.jpg",
  "./assets/cards/wood-03.jpg",
  "./assets/cards/wood-04.jpg",
  "./assets/cards/wood-05.jpg",
  "./assets/cards/wood-06.jpg",
  "./assets/cards/wood-07.jpg",
  "./assets/cards/wood-08.jpg",
  "./assets/cards/wood-09.jpg",
  "./assets/cards/wood-10.jpg",
  "./assets/cards/wood-11.jpg",
  "./assets/cards/wood-12.jpg",
  "./assets/cards/wood-13.jpg",
  "./assets/cards/wood-14.jpg",
  "./assets/cards/wood-15.jpg",
  "./assets/cards/wood-16.jpg",
  "./assets/cards/wood-17.jpg",
  "./assets/cards/wood-18.jpg",
  "./assets/cards/wood-19.jpg",
  "./assets/vfx/darkness-orb.png",
  "./assets/vfx/earth-impact.png",
  "./assets/vfx/earth-spell.png",
  "./assets/vfx/explosion.png",
  "./assets/vfx/fire-spell.png",
  "./assets/vfx/fire-wrath.png",
  "./assets/vfx/fireball.png",
  "./assets/vfx/firebomb.png",
  "./assets/vfx/ice-lance.png",
  "./assets/vfx/light-bolt.png",
  "./assets/vfx/light-pillar.png",
  "./assets/vfx/magic-circle.png",
  "./assets/vfx/magic-sparks.png",
  "./assets/vfx/metal-lightning.png",
  "./assets/vfx/nature-heal.png",
  "./assets/vfx/plant-missile.png",
  "./assets/vfx/portal.png",
  "./assets/vfx/rock-sling.png",
  "./assets/vfx/shield.png",
  "./assets/vfx/shockwave.png",
  "./assets/vfx/slash-blue.png",
  "./assets/vfx/slash-fire.png",
  "./assets/vfx/slash-gold.png",
  "./assets/vfx/slash-small.png",
  "./assets/vfx/splash.png",
  "./assets/vfx/water-blast.png",
  "./assets/vfx/water-magic.png",
  "./assets/vfx/wood-spell.png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const path = new URL(event.request.url).pathname;
  if (path.endsWith("/victory-messages.php") || path.endsWith("/auth.php")) return;
  event.respondWith(
    fetch(event.request).then((response) => {
        const copy = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        return response;
      }).catch(() => caches.match(event.request).then((cached) => cached || caches.match("./index.html")))
  );
});
